### ISSUE TITLE
Very slight edits to reflect explicit rclone support at rsync.net

### ISSUE THREAD

**Issue by rsyncnet** [hacker-tools/hacker-tools.github.io#13]
Friends,

Thank you for noting the explicit support (and reduced pricing) for borg/attic on the rsync.net cloud storage platform.  Appreciated - and we continue to very enthusiastically support that tool.

I wonder if you would change the link you have from this one:

https://www.rsync.net/products/attic.html

to this one:

https://www.rsync.net/products/borg.html

ALSO, I am happy to note that we deployed the rclone binary across all rsync.net storage servers (it requires a server side component) which means we have explicit support for rclone - if you feel it is appropriate, could you add "rsync.net" to this list of rclone targets:

"... like rsync but for cloud storage providers such as Amazon S3, Dropbox, Google Drive ..."

Many thanks.

**Comment by anishathalye** [comment]
Sure! Done in b0d857fc10da1676001989479646be21494f783a.
